### ISSUE TITLE
Useless wihtout working examples

### ISSUE THREAD

**Issue by TagoriaTar** [progzdeveloper/QtExtra#1]
The widgets looks nice here on github, but without working examples useless. On Qt 5.14.2 i got tons of errors when compiling the examples and there are no readmes that could help.
:-1: error: cannot find -lqtcoreextrad
:-1: error: cannot find -lqtsqlextrad
:-1: error: cannot find -lqtwidgetsextrad

**Comment by progzdeveloper** [comment]
Thanks for feedback! 
First of all it wasn't tested aganist Qt 5.14.2 yet, but it should work anyway. 
If you compile with Qt Creator try to disable shadow build in project properties, this can resolve the issue. 
Also, you can find working examples in QtExtra/examples folder.
